### ISSUE TITLE
Add test coverage pre-commit hook

### ISSUE THREAD

**Issue by dreamgonfly** [pretraining/template#32]
Add a pre-commit hook for measuring test coverage

**Comment by alxiom** [comment]
`requirements.txt`에 `pytest` 추가해야 할 것 같네요?

**Comment by bzantium** [comment]
> `requirements.txt`에 `pytest` 추가해야 할 것 같네요?

`coverage`도 추가해야할 것 같습니다만 PR에서 보섭님이 말씀하신 것처럼 pytest-cov 이용하면 필요없을 것 같네요.
