### ISSUE TITLE
설정을 setup.cfg로 관리

### ISSUE THREAD

**Issue by aisolab** [pretraining/template#34]
## 개요
static analysis 또는 lint에 관련된 설정을 `setup.cfg`로 관리하는 것은 어떨는 지요? 통합적으로 한방에 기입하고 쓸 수 있어서 저는 `pyproject.toml`보다는 좀 선호하는 편입니다.

![image](https://user-images.githubusercontent.com/19755607/110560868-0c7e3600-818a-11eb-853f-82966f988377.png)

cc: @pretraining/authors

**Comment by bzantium** [comment]
huggingface/transformers를 참고하니 black support 를 위해 pyproject.toml 도 사용하여 두 개를 같이 사용하고 있는데 이와 같이 이용하는 것은 어떨까요?

**Comment by bzantium** [comment]
> > huggingface/transformers를 참고하니 black support 를 위해 pyproject.toml 도 사용하여 두 개를 같이 사용하고 있는데 이와 같이 이용하는 것은 어떨까요?
> > ![image](https://user-images.githubusercontent.com/19511788/110564148-ba401380-818f-11eb-804f-5bb03888bb1a.png)
> 
> `black`의 경우 `brunette`를 활용하면 똑같이 활용할 수 있습니다!
> 
> https://github.com/odwyersoftware/brunette

오 그러면 setup.cfg 만으로 처리 가능하겠네요! 저는 좋은 것 같습니다.

**Comment by aisolab** [comment]
@bzantium 제가 한번 pr 날려볼게요 ㅎㅎ

**Comment by aisolab** [comment]
> > @bzantium 제가 한번 pr 날려볼게요 ㅎㅎ
> 
> [tool.isort]
> profile = "black"
> 
> conflict 해소를 위해서 위 설정을 추가하는 것은 어떨까요?

오잉 이건 어떤 의미일까요?? 저는 일단
https://black.readthedocs.io/en/stable/compatible_configs.html
기준으로 설정하려고 했습니다.
